### ISSUE TITLE
Error: lsys_input.tab.c:280:10: fatal error: lsys_input.tab.h: No such file or directory

### ISSUE THREAD

**Issue by ouening** [AlgorithmicBotany/vlab#4]
**OS: Ubuntu22.04**

I encounted an error during compiling:
*lsys_input.tab.c:280:10: fatal error: lsys_input.tab.h: No such file or directory*

Some dependences have been changed:
![image](https://github.com/user-attachments/assets/2ede5457-1cf7-4a4a-9918-05f0b990ac31)

How could I solve this issue?

**Comment by mikcieslak** [comment]
I've had the same issue, but I was not able to find a simple fix. For now, the easiest way to to add the missing files to the repo. Please pull the code again and try recompiling. I've included a few other fixes for compiling on Ubuntu22.04

**Comment by ouening** [comment]
The error still exists:
![image](https://github.com/user-attachments/assets/a13ba299-2a50-4b6b-aff7-dcb7fb6cdaf2)

**Comment by mikcieslak** [comment]
Thanks for testing. I forgot that this quick fix requires changing the Makefile. At any rate, I implemented a better solution by modifying the Qt project file. The problem is coming from different versions of bison on Ubuntu 20.04 and 22.04, which breaks the way qmake generates the tab.c/.h files. Please pull the repo and try again.
BTW, for now, Rayshade does not seem to compile on Ubuntu 22.04. If you haven't done this already, I'd recommend removing Rayshade from the vlab.pro file.

**Comment by ouening** [comment]
It works now! Thanks very much!
